# manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycv-deployment
spec:
  selector:
    matchLabels:
      app: mycv-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mycv-server
    spec:
      containers:
        - name: httpd-container
          image: docker.io/salvav/angularcv:latest
          imagePullPolicy: IfNotPresent  
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mycv-service
  name: mycv-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mycv-server
  type: LoadBalancer


